In [ ]:
import os as os
from os.path import dirname, join as pjoin
import scipy.io as sio
import pandas as pd
import matlab.engine

def loadmat(tbasepath):
    dfmetadata =[]
    dfb =[]

    for file in os.listdir(tbasepath+"/matfiles/"):
        print(file)
        eng = matlab.engine.start_matlab()
        mat_contents = eng.eval("load('" + tbasepath +"/matfiles/" + file + "')")
        meta_data = mat_contents['meta_data']
        sample_time = pd.DataFrame(eng.getfield(meta_data,"sample_time"))
        sample_type = pd.DataFrame(eng.getfield(meta_data,"sample_type"))
        ml_analyzed = pd.DataFrame(eng.getfield(meta_data,"ml_analyzed"))
        tag1 = pd.DataFrame(eng.getfield(meta_data,"tag1"))
        cruise = pd.DataFrame(eng.getfield(meta_data,"cruise"))
        skip = pd.DataFrame(eng.getfield(meta_data,"skip"))

        dfmd = pd.concat([sample_time,sample_type,ml_analyzed,cruise,tag1,skip],axis = 1)

        dfmd.columns = ["sample_time","sample_type","ml_analyzed","cruise","tag1","skip"]

        class2use = pd.DataFrame(mat_contents['class2use'])[0]
        biovol = pd.DataFrame(mat_contents['classbiovol_above_adhocthresh'])
        matdates = pd.DataFrame(mat_contents['mdate'])
        filelist = pd.DataFrame(mat_contents['filelist'])
        biovol.columns = class2use

        dfbiovol = pd.concat([dfmd["sample_time"],biovol],axis = 1)
        dfbiovol.rename(columns = {0:"matdate"},inplace = True)


        dfmetadata.append(dfmd)
        dfb.append(dfbiovol)

    dfmetadata = pd.concat(dfmetadata)
    dfb = pd.concat(dfb)
    dfmetadata.to_csv(tbasepath + "/dfmetadata.csv")
    dfb.to_csv(tbasepath + "/dfbiovolume.csv")
    
loadmat("/D/MIT-WHOI/github_repos/preliminary_data/data/transect/")
loadmat("/D/MIT-WHOI/github_repos/preliminary_data/data/broadscale/")

summary_biovol_allHDF_min20_2017.mat
summary_biovol_allHDF_min20_2018.mat
summary_biovol_allHDF_min20_2019.mat
summary_biovol_allHDF_min20_2020.mat
summary_biovol_allHDF_min20_2021.mat

In [106]:
tbasepath = "/D/MIT-WHOI/github_repos/preliminary_data/data/broadscale/"
file = os.listdir(tbasepath+"matfiles/")[0]
print(file)
eng = matlab.engine.start_matlab()
mat_contents = eng.eval("load('" + tbasepath +"/matfiles/" + file + "')")

summary_biovol_allHDF_min20_2013.mat

In [101]:
tbasepath = "/D/MIT-WHOI/github_repos/preliminary_data/data/broadscale/"
dfmetadata =[]
dfb =[]

file = os.listdir(tbasepath+"matfiles/")[0]
print(file)
eng = matlab.engine.start_matlab()
mat_contents = eng.eval("load('" + tbasepath +"/matfiles/" + file + "')")
meta_data = mat_contents['meta_data']
sample_time = pd.DataFrame(eng.getfield(meta_data,"sample_time"))
sample_type = pd.DataFrame(eng.getfield(meta_data,"sample_type"))
ml_analyzed = pd.DataFrame(eng.getfield(meta_data,"ml_analyzed"))
tag1 = pd.DataFrame(eng.getfield(meta_data,"tag1"))
cruise = pd.DataFrame(eng.getfield(meta_data,"cruise"))
skip = pd.DataFrame(eng.getfield(meta_data,"skip"))

dfmd = pd.concat([sample_time,sample_type,ml_analyzed,cruise,tag1,skip],axis = 1)

dfmd.columns = ["sample_time","sample_type","ml_analyzed","cruise","tag1","skip"]

class2use = pd.DataFrame(mat_contents['class2use'])[0]
biovol = pd.DataFrame(mat_contents['classbiovol_above_adhocthresh'])
matdates = pd.DataFrame(mat_contents['mdate'])
filelist = pd.DataFrame(mat_contents['filelist'])
biovol.columns = class2use

dfbiovol = pd.concat([dfmd["sample_time"],biovol],axis = 1)
dfbiovol.rename(columns = {0:"matdate"},inplace = True)

summary_biovol_allHDF_min20_2013.mat

In [102]:
dfbiovol.head()

,sample_time,Acanthoica_quattrospina,Akashiwo,Alexandrium_catenella,Amphidinium,Amylax,Apedinella,Asterionellopsis_glacialis,Bacillaria,Bacillariophyceae,...,mix,pennate,pennate_Pseudo-nitzschia,pennate_Thalassionema,pennate_morphotype1,pollen,shellfish_larvae,square_unknown,unknown2,zooplankton
0,2013-08-21 17:17:09+00:00,0.0,0.0,31731.081325,0.0,0.000000,382.230282,0.0,0.0,208.340070,...,43046.241507,0.000000,0.0,0.0,0.0,0.0,0.0,186.502166,9327.558194,0.0
1,2013-08-23 16:09:01+00:00,0.0,0.0,0.000000,0.0,0.000000,125.615817,0.0,0.0,13.433305,...,10564.943556,317.297572,0.0,0.0,0.0,0.0,0.0,0.000000,15305.437822,0.0
2,2013-08-23 20:48:28+00:00,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,911.681412,...,52627.893381,34.661984,0.0,0.0,0.0,0.0,0.0,0.000000,24948.104358,0.0
3,2013-08-24 21:13:57+00:00,0.0,0.0,9576.573945,0.0,0.000000,0.000000,0.0,0.0,159.188575,...,55949.930177,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
4,2013-08-24 21:34:33+00:00,0.0,0.0,0.000000,0.0,6564.132154,361.758279,0.0,0.0,0.000000,...,9622.690033,0.000000,0.0,0.0,0.0,0.0,0.0,361.756552,535010.679628,0.0

In [104]:
dfmetadata.append(dfmd)
dfb.append(dfbiovol)

dfmetadata = pd.concat(dfmetadata)
dfb = pd.concat(dfb)
dfmetadata.to_csv(tbasepath + "/dfmetadata.csv",index_label = False)
dfb.to_csv(tbasepath + "/dfbiovolume.csv",index_label = False)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"